dubbo:
  application:
    name: email_service
  registry:
    address: zookeeper://120.25.244.38:2181
  protocol:
    port: -1


spring:
  mail:
    #配置发送方协议
    protocol: smtp
    #配置smtp服务器地址
    host: smtp.sina.cn
    #发送方的邮箱
    username: verygoodwlk@sina.cn
    #发送方的密码
    password: ken123456

